start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 9

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus on focused monitor/window change
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# Gaps between windows (inner) and between monitor edges (outer).
[gaps]
inner.horizontal = 15
inner.vertical   = 15
outer.left       = 15
outer.bottom     = 15
outer.top        = 15
outer.right      = 15

[mode.main.binding]
# Layouts  
cmd-alt-tab = 'layout tiles accordion'

# Focus 
cmd-left  = 'focus left'
cmd-down  = 'focus down'
cmd-up    = 'focus up'
cmd-right = 'focus right'

# Window Movements 
cmd-alt-left  = 'move left'
cmd-alt-down  = 'move down'
cmd-alt-up    = 'move up'
cmd-alt-right = 'move right'

# Workspaces   
alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'

# Move node to Workspace  
cmd-alt-0 = 'move-node-to-workspace 0'
cmd-alt-1 = 'move-node-to-workspace 1'
cmd-alt-2 = 'move-node-to-workspace 2'
cmd-alt-3 = 'move-node-to-workspace 3'

# Resize
alt-right = 'resize smart -50'
alt-left  = 'resize smart +50'
alt-up    = 'resize smart +50'
alt-down  = 'resize smart -50'

# Sevice Mode  
cmd-alt-s = 'mode service'

# Service Mode Actions & App Launchers
[mode.service.binding]
r = ['reload-config', 'mode main']
f = ['exec-and-forget open -a "Finder"',   'mode main']
e = ['exec-and-forget open -a "Mail"',     'mode main']
w = ['exec-and-forget open -a "WezTerm"',  'mode main']
v = ['exec-and-forget open -a "vsCode"',   'mode main']
s = ['exec-and-forget open -a "Safari"',   'mode main']
y = ['exec-and-forget open -a "YouTube"',  'mode main']
n = ['exec-and-forget open -a "Stickies"', 'mode main']
m = ['exec-and-forget open -a "Music"',    'mode main']

# App to Workspace assignments
[[on-window-detected]]
if.app-name-regex-substring = 'Stickies|Music'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-name-regex-substring = 'WezTerm|vsCode'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Safari'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'YouTube'
run = 'move-node-to-workspace 3'
